
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditLibrarianChooser.java
 *
 * Created on Dec 22, 2011, 4:52:58 PM
 */
/**
 *
 * @author david
 */
public class EditLibrarianChooser extends javax.swing.JPanel {
    dataManager dat;
    /** Creates new form EditLibrarianChooser */
    public EditLibrarianChooser(dataManager dat) {
        this.dat = dat;
        initComponents();
        
        librarian_list.setListData(dat.getLibrarians());
        
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        librarian_list = new javax.swing.JList();
        search_field = new javax.swing.JTextField();
        button_search = new javax.swing.JButton();
        edit_librarian = new javax.swing.JButton();
        back_button = new javax.swing.JButton();

        jLabel1.setText("Choose Librarian to Edit");

        librarian_list.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(librarian_list);

        button_search.setText("Search");
        button_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                button_searchMouseReleased(evt);
            }
        });

        edit_librarian.setText("Edit Librarian");
        edit_librarian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                edit_librarianMouseReleased(evt);
            }
        });

        back_button.setText("Back To Panel");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(255, 255, 255)
                        .add(jLabel1))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(search_field, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 277, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(button_search))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 401, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(edit_librarian)
                            .add(back_button))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(25, 25, 25)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(search_field, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(button_search))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .add(edit_librarian)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(back_button))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 293, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void button_searchMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_searchMouseReleased
        String login = search_field.getText();
        try{
            int[] type = {0, 0, 1};
            Vector<String> vector;
            
            vector = dat.searchUser(login, type);
            
            
            if (vector.isEmpty()) {
                String[] temp = {"A procura não encontrou resultados"};
                librarian_list.setListData(temp);
            } else {
                librarian_list.setListData(vector);
            }
        } catch (SQLException ex) {
            //Logger.getLogger(DeleteUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_button_searchMouseReleased

    private void edit_librarianMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_librarianMouseReleased
        Object[] selected = librarian_list.getSelectedValues();         
        if (selected.length == 1 && selected[0].equals("A procura não encontrou resultados")); 
        //do nothing         
        else {             
            for (int i = 0; i < selected.length; i++) {                 
                try {                     
                    dat.removeUser("" + dat.getLibrarian((String) selected[i]).getId());                 
                } catch (SQLException ex) {                     
                    //Logger.getLogger(DeleteUser.class.getName()).log(Level.SEVERE, null, ex);                 
                }
            }             
             librarian_list.setListData(dat.getReaders());        
        }
        
    }//GEN-LAST:event_edit_librarianMouseReleased
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button;
    private javax.swing.JButton button_search;
    private javax.swing.JButton edit_librarian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList librarian_list;
    private javax.swing.JTextField search_field;
    // End of variables declaration//GEN-END:variables
}
