
import java.util.Vector;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ManageReservations.java
 *
 * Created on Nov 22, 2011, 2:47:19 AM
 */
/**
 *
 * @author jlnabais
 */
public class ManageReservations extends javax.swing.JFrame {

    Library dat;
    /** Creates new form ManageReservations */
    public ManageReservations() {
        this.dat = Library.Instance();
        initComponents();
        
        Vector <String> v1 = dat.expiredReservations();
        if(v1.size() == 0){
            String [] temp = {"There are no expired reservations."};
            expired_list.setListData(temp);
        }
        else{
            expired_list.setListData(v1);
        }
        
        Vector <String> v2 = dat.expiringReservations(3);
        if(v2.size() == 0){
            String [] temp = {"There are no critical reservations."};
            critical_list.setListData(temp);
        }
        else{
            critical_list.setListData(v2);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        add_reservation = new javax.swing.JButton();
        delete_reservation = new javax.swing.JButton();
        librarians_panel = new javax.swing.JButton();
        edit_reservation = new javax.swing.JButton();
        tab_panel = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        critical_list = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        expired_list = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Manage Reservations");

        add_reservation.setText("Add Reservation");
        add_reservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_reservationActionPerformed(evt);
            }
        });

        delete_reservation.setText("Delete Reservation");
        delete_reservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_reservationActionPerformed(evt);
            }
        });

        librarians_panel.setText("Librarian's Panel");
        librarians_panel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librarians_panelActionPerformed(evt);
            }
        });

        edit_reservation.setText("Edit Reservation");
        edit_reservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_reservationActionPerformed(evt);
            }
        });

        critical_list.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(critical_list);

        tab_panel.addTab("Critical Reservations", jScrollPane1);

        expired_list.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(expired_list);

        tab_panel.addTab("Expired Reservations", jScrollPane2);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(33, 33, 33)
                        .add(tab_panel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 514, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(add_reservation, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .add(edit_reservation, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, delete_reservation, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                        .add(42, 42, 42))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(299, 299, 299)
                        .add(jLabel1)))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(570, 570, 570)
                .add(librarians_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .add(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(48, 48, 48)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(add_reservation)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(edit_reservation)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(delete_reservation))
                    .add(tab_panel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 384, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(17, 17, 17)
                .add(librarians_panel)
                .add(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void add_reservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_reservationActionPerformed
// TODO add your handling code here:
    new AddReservation().setVisible(true);
    dispose();
}//GEN-LAST:event_add_reservationActionPerformed

private void delete_reservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_reservationActionPerformed
// TODO add your handling code here:
    new DeleteReservation().setVisible(true);
    dispose();
}//GEN-LAST:event_delete_reservationActionPerformed

private void librarians_panelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librarians_panelActionPerformed
// TODO add your handling code here:
    new LibrarianForm().setVisible(true);
    dispose();
}//GEN-LAST:event_librarians_panelActionPerformed

private void edit_reservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_reservationActionPerformed
// TODO add your handling code here:
    new EditReservation().setVisible(true);
    dispose();
}//GEN-LAST:event_edit_reservationActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_reservation;
    private javax.swing.JList critical_list;
    private javax.swing.JButton delete_reservation;
    private javax.swing.JButton edit_reservation;
    private javax.swing.JList expired_list;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton librarians_panel;
    private javax.swing.JTabbedPane tab_panel;
    // End of variables declaration//GEN-END:variables
}
