/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ManageReservations.java
 *
 * Created on Nov 22, 2011, 2:47:19 AM
 */
/**
 *
 * @author jlnabais
 */
public class ManageReservations extends javax.swing.JFrame {

    dataManager dat;
    /** Creates new form ManageReservations */
    public ManageReservations(dataManager dat) {
        this.dat = dat;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        search_reservations = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        add_reservation = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_field = new javax.swing.JList();
        delete_reservation = new javax.swing.JButton();
        librarians_panel = new javax.swing.JButton();
        edit_reservation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Manage Reservations");

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        add_reservation.setText("Add Reservation");
        add_reservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_reservationActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(list_field);

        delete_reservation.setText("Delete Reservation");
        delete_reservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_reservationActionPerformed(evt);
            }
        });

        librarians_panel.setText("Librarian's Panel");
        librarians_panel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librarians_panelActionPerformed(evt);
            }
        });

        edit_reservation.setText("Edit Reservation");
        edit_reservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_reservationActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(33, 33, 33)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 491, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(36, 36, 36)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(librarians_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .add(add_reservation, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .add(edit_reservation, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, delete_reservation, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)))
                            .add(layout.createSequentialGroup()
                                .add(search_reservations, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 441, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(26, 26, 26)
                                .add(search, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(layout.createSequentialGroup()
                        .add(299, 299, 299)
                        .add(jLabel1)))
                .addContainerGap(26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(search_reservations, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(search))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .add(add_reservation)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(edit_reservation)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(delete_reservation)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(librarians_panel))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 354, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void add_reservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_reservationActionPerformed
// TODO add your handling code here:
    new AddReservation(dat).setVisible(true);
    dispose();
}//GEN-LAST:event_add_reservationActionPerformed

private void delete_reservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_reservationActionPerformed
// TODO add your handling code here:
    new DeleteReservation(dat).setVisible(true);
    dispose();
}//GEN-LAST:event_delete_reservationActionPerformed

private void librarians_panelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librarians_panelActionPerformed
// TODO add your handling code here:
    new LibrarianForm(dat).setVisible(true);
    dispose();
}//GEN-LAST:event_librarians_panelActionPerformed

private void edit_reservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_reservationActionPerformed
// TODO add your handling code here:
    new EditReservation(dat).setVisible(true);
    dispose();
}//GEN-LAST:event_edit_reservationActionPerformed

private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_searchActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_reservation;
    private javax.swing.JButton delete_reservation;
    private javax.swing.JButton edit_reservation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton librarians_panel;
    private javax.swing.JList list_field;
    private javax.swing.JButton search;
    private javax.swing.JTextField search_reservations;
    // End of variables declaration//GEN-END:variables
}
